version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: imrobot_monitor
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
  redis:
    image: redis:5-alpine
    restart: always
    ports:
      - 6381:6379
  # client:
  #   build: ./apps/client
  #   restart: always
  #   ports:
  #     - 3000:3000
  # serve:
  #   build: ./
  #   restart: always
  #   ports:
  #     - 3001:3001
  #   depends_on:
  #     - mysql
  #     - redis
  #   environment:
  #     - DATABASE_URL=mysql://root:password@host.docker.internal:3308/imrobot_monitor
  