version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: imrobot_monitor
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "4306:3306"
  redis:
    image: redis:5-alpine
    restart: always
    ports:
      - 4379:6379
  client:
    image: reinerlau/imrobot-monitor-client:latest
    restart: always
    ports:
      - 4000:3000
  server:
    image: reinerlau/imrobot-monitor-server:latest
    restart: always
    ports:
      - 4001:3001
    depends_on:
      - mysql
      - redis
    environment:
      - DATABASE_URL=mysql://root:password@host.docker.internal:4306/imrobot_monitor